package proto

// msg type
const (
	WX_MSG_TYPE_TEXT  = 1
	WX_MSG_IMG_TEXT   = 2
	WX_MSG_CARD_TEXT  = 42
	WX_MSG_VOICE_TEXT = 34
)

const (
	FRINEDS_CIRCLE_IMG   = "img"
	FRINEDS_CIRCLE_VIDEO = "video"
)

const (
	TASK_ID_CONTACTS_MASS  = 1
	TASK_ID_FRIENDS_CIRCLE = 2
	TASK_ID_ATTENTION_CARD = 3
)
